config/routes.rb
Portfolio::Application.routes.draw do

  scope ":locale" do
    devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
    resources :posts do
      resources :comments
    end
    resources :projects do
      resources :comments
    end
  end

  root :to => "welcome#index"

  root :to => 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :comments, as: :commentable
  attr_accessible :name, :technologies_used, :image, :remote_image_url, :description

  validates :technologies_used, presence:true
  validates :name, length: { in: 4..255 }
  mount_uploader :image, ImageUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  run = true

  def index
    @projects = Project.all

  end

  def new
    @project = Project.new

  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      respond_to do |format|
        format.html { redirect_to @project, notice: 'Project was successfully added.' }
        format.js
      end
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      respond_to do |format|
        format.html { redirect_to @project, notice: 'Project was successfully updated' }
        format.js
      end
    else
        render :edit
    end

  end

  def destroy
    @project = Project.destroy(params[:id])

    respond_to do |format|
      format.html { redirect_to @project, notice: 'Project was successfully deleted' }
      format.js
    end
  end
end

app/views/projects/_form.html.erb
<div class="well" id="project_form">
  <fieldset>
<%= form_for(@project, remote: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br/>
    <%= f.text_area :description, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :technologies_used %><br/>
    <%= f.text_field :technologies_used, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
    <%= f.label :remote_image_url, "or image URL" %>
    <%= f.text_field :remote_image_url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= link_to 'Back', projects_path, :class => 'btn btn-default' %>
    <%= f.submit :class => 'btn btn-primary'%>
  </div>
<% end %>
</fieldset>
</div>

app/views/projects/_project.html.erb
<div class="row" id="<%= dom_id(project) %>">
  <div class="col-lg-7 col-md-7">
    <%= image_tag project.image_url(:thumb).to_s, :class => 'img-responsive' %>
  </div>
  <div class="col-lg-5 col-md-5">
    <h3><%= link_to project.name, project %></h3>
    <p><%= project.description %></p>
    <p><%= project.technologies_used %></p>
    <% if current_user.present? %>
      <%= link_to 'Edit', edit_project_path(project), remote: true, :class => 'btn btn-primary' %>
      <%= link_to 'Destroy', project, method: :delete, data: {confirm: 'Are you sure?'}, remote: true, :class => 'btn btn-warning' %>
    <% end %>
  </div>
</div>

app/views/projects/back.js.erb
$('#project_form').remove()

app/views/projects/create.js.erb
$('#new_project_link').show()
$('#project_form').remove()
// show the new project that was added
$('#projects:last').after('<%=j render(@project) %>')

app/views/projects/destroy.js.erb
$('#project_<%= @project.id %>').remove()

app/views/projects/edit.html.erb
<div class = "container-blog">
  <h1>Edit Project</h1>

  <%= render "form" %>
</div>

app/views/projects/edit.js.erb
// horrible temp fix
$('#project_form').after('<%=j render(@project) %>');
$('#project_form').remove()
//

$('#project_<%= @project.id %>').after('<%= j render("form") %>');
$('#project_<%= @project.id %>').remove()

app/views/projects/index.html.erb
<div class = "container-blog">
  <div class="page-header" id="projects">
    <h1>Projects</h1>
  </div>

  <%= render @projects %>

  <div class="row">
    <% if current_user.present? %>
      <%= link_to 'New project', new_project_path, id: "new_project_link", remote: true, :class => 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class = "container-blog">
  <h1>New project</h1>

  <%= render "form" %>
</div>

app/views/projects/new.js.erb
// horrible temp fix
$('#project_form').remove()
//

$('#new_project_link').hide().after('<%= j render("form") %>');

app/views/projects/show.html.erb
<div class = "container-blog">
  <h2><%= @project.name %></h2>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= image_tag @project.image_url.to_s, :class => 'img-responsive' %>
      <p><b>Technologies used:</b>
      <%= @project.technologies_used %>
    </div>
  </div>

  <%= link_to 'Back', projects_path, :class => 'btn btn-default' %>
</div>

app/views/projects/update.js.erb
$('#project_form').after('<%=j render(@project) %>');
$('#project_form').remove()