config/routes.rb
Portfolio::Application.routes.draw do

  scope ":locale" do
    devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
    resources :posts do
      resources :comments
    end
    resources :projects do
      resources :comments
    end
  end

  root :to => "welcome#index"

  root :to => 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable
  attr_accessible :body, :title, :published
  scope :published, where(published: true)

  def publish!
    published = true
    save!
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @posts = policy_scope(Post)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    @commentable = @post
    @comments = policy_scope(@post.comments)
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    authorize @post
    current_user.posts << @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    authorize @post

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/views/posts/_form.html.erb
<div class="well">
  <fieldset>
<%= simple_form_for(@post) do |f| %>
  <%= f.input :title%>
  <%= f.input :body%>
<% end %>
</fieldset>
</div>

<script type="text/javascript">
  $(document).ready(function(){

    $('#post_body').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/posts/edit.html.erb
<div class = "container-blog">
  <h1>Editing post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class = "container-blog">
  <div class="page-header">
  <h1>Blog</h1>
  </div>
  <div class="row">
    <div class="col-lg-8 col-md-8">
      <% @posts.reverse_each do |post| %>
        <id="<%= dom_id(post) %>">
          <h3><%= post.title %></h3>

          <div class="panel panel-default">
            <div class="panel-body">
            <%= post.body.html_safe %> <br /><br />

          <%= link_to 'Show', post, :class => 'btn btn-default' %>
          <% if policy(post).update? %>
            <%= link_to 'Edit', edit_post_path(post), :class => 'btn btn-primary' %>
          <% end %>
          <% if post.published? == false && policy(post).publish?%>
            <%= link_to 'Publish', post_path(post, post: { published: true }), method: :put, data: { confirm: 'Are you sure you want to publish?'}, :class => 'btn btn-warning'%>
          <% end %>
          <% if post.published? && policy(post).publish?%>
            <%= link_to 'Unpublish', post_path(post, post: { published: false }), method: :put, data: { confirm: 'Are you sure you want to unpublish?'}, :class => 'btn btn-warning' %>
          <% end %>
          <% if policy(post).destroy? %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'%>
          <% end %>
          </div>
          </div>
      <% end %>

      <% if current_user.present? %>
      <%= link_to 'New Post', new_post_path, :class => 'btn btn-default'%>
      <% end %>
    </div>
    <div class="col-lg-4 col-md-4">

      </a>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class = "container-blog">
  <h1>New post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class = "container-blog">
  <p id="notice"><%= notice %></p>
  <h1><%= @post.title %></h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <p id="author">
        <b>By:</b>
        <%= @post.author.email %>
        <br/>
        <b>Date:</b>
        <%= l @post.created_at, format: :short %>
      </p>
      <p>
        <b>Body:</b><br />
        <%= @post.body.html_safe %>
      </p>

    </div>
  </div>
  <%= render 'comments/show' %>

  <%= render 'comments/form' %>


  <%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-primary' %>
  <%= link_to 'Back', posts_path, :class => 'btn btn-default' %>
</div>